package com.chokavo.chosportsman.ormlite.models;

import com.j256.ormlite.field.DatabaseField;
import com.j256.ormlite.table.DatabaseTable;

/**
 * Created by ilyapyavkin on 13.04.16.
 * Many 2 many connection between sportsman and favorite sporttype
 */
@DatabaseTable(tableName = "sportsman_fav_sporttype")
public class SportsmanFavSportType {
    public final static String SPORTSMAN_ID_FIELD_NAME = "sportsman_id";
    public final static String SPORTTYPE_ID_FIELD_NAME = "sporttype_id";

    /**
     * This id is generated by the database and set on the object when it is passed to the create method. An id is
     * needed in case we need to update or delete this object in the future.
     */
    @DatabaseField(generatedId = true)
    int id;

    // This is a foreign object which just stores the id from the User object in this table.
    @DatabaseField(foreign = true, columnName = SPORTSMAN_ID_FIELD_NAME)
    Sportsman sportsman;

    // This is a foreign object which just stores the id from the Post object in this table.
    @DatabaseField(foreign = true, columnName = SPORTTYPE_ID_FIELD_NAME)
    SSportType sportType;

    SportsmanFavSportType() {
        // for ormlite
    }

    public SportsmanFavSportType(Sportsman sportsman, SSportType sportType) {
        this.sportsman = sportsman;
        this.sportType = sportType;
    }
}
